{% set name = "triad" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c27d31219698f31e0a1f2073a9c580f4c21c1b0f0e7c42b7a1c3eb222da7db19

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - fs
    - fsspec >=2022.5.0
    - importlib-metadata
    - numpy
    - pandas >=1.3.5
    - packaging
    - pyarrow >=6.0.1
    - six

test:
  imports:
    - triad
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/fugue-project/triad
  license: Apache-2.0
  license_file: LICENSE
  summary: A collection of python utility functions for Fugue projects
  doc_url: https://triad.readthedocs.org
  dev_url: https://github.com/fugue-project/triad

extra:
  recipe-maintainers:
    - charlesbluca
    - thewchan
    - kvnkho
    - goodwanghan
    - rdmolony
