{% set name = "triad" %}
{% set version = "0.9.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4a54f3ccb23b47eb7df940ab1aac209c0e056417a086029f4d2adb38502ac451

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - fs
    - fsspec >=2022.5.0
    - importlib_metadata
    - numpy
    - pandas >=1.3.5
    - packaging
    - pyarrow >=6.0.1
    - six

test:
  imports:
    - triad
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/fugue-project/triad
  license: Apache-2.0
  license_file: LICENSE
  summary: A collection of python utility functions for Fugue projects
  doc_url: https://triad.readthedocs.org
  dev_url: https://github.com/fugue-project/triad

extra:
  recipe-maintainers:
    - charlesbluca
    - thewchan
    - kvnkho
    - goodwanghan
    - rdmolony
